module.exports = {
	siteName: "MitMach Agentur",
	domain: "www.mitmach-agentur.de",
	logo: "logo.png",
	logopie: "logopie.png",
	email: "info@mitmach-agentur.de",
	tel: {
		land: "",
		landFormatted: "",
		mobile: "+4917631796400",
		mobileFormatted: "017631796400",
	},
	address: {
		lineOne: "Hallostr. 193",
		lineTwo: "",
		city: "Essen",
		state: "",
		zip: "45309 ",
		mapLink: "https://maps.app.goo.gl/9cpwoC82KjU19JHx7",
	},
	social: {
		rss: "",
		whatsapp: "",
		facebook: "https://www.facebook.com/mitmach.agentur",
		twitter: "",
		instagram: "https://www.instagram.com/mitmach.agentur/",
		linkedin: "",
		youtube: "",
		tiktok: "",
		pinterest: "",
		skype: "",
		mastodon: "",
		discord: "",
		github: "",
		slideshare: "",
		flickr: "",
		vimeo: "",
		telegram: "",
	},
	legal: {
		nombreLegal: "mitMach Agentur gUG",
		nif: "",
		direccionFiscal: "Hallostr. 193. 45309 Essen",
		emailLegal: "info@mitmach-agentur.de",
		tfnoLegal: "017631796400",
		datosRegistrales:
			"Handelsregister: 34906. Registergericht: Amtsgericht Essen",
	},
};
